name: Spigot-Basics
author: mrteacup
main: main.Main
version: 1.0
api-version: 1.13
commands:
    random:
        description: generiert Zufallszahlen 
        usage: /<random>
    jump:
        description: schleudert dich in die Luft
        usage: /<jump>